name: core release

on:
  push:
    paths:
      - 'core/**'
    tags: [ 'core/*' ]
    branches:
      - '*'
jobs:
  test:
    name: ${{ matrix.config.kind }} ${{ matrix.config.os }}
    runs-on: ubuntu-latest-4-cores
    environment: CI
    strategy:
      matrix:
        deno-version: [1.44.4]
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Git Checkout Core
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Lint Deno Module
        working-directory: core
        run: |
          deno fmt --check
          deno lint
      - name: Test Deno Module
        working-directory: core
        env:
          TMPDIR: ${{ runner.temp }}
          CI: true
          NGS_CI_USER: ${{ secrets.NGS_CI_USER }}
        run: |
          deno task test


